//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp19
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class glazyrinDanilEntities : DbContext

    {
        private static glazyrinDanilEntities _context;
        public static glazyrinDanilEntities GetContext()
        {
            if (_context == null)
            {
                _context = new glazyrinDanilEntities();

            }
            return _context;
        }

        public glazyrinDanilEntities()
            : base("name=glazyrinDanilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Каталог> Каталог { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
    }
}
