//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Каталог
    {
        public int id { get; set; }
        public string Бренд { get; set; }
        public string Адрес { get; set; }
        public string Характеристики { get; set; }
        public Nullable<int> Стоимость { get; set; }
    }
}
