//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public int id { get; set; }
        public string ФИО { get; set; }
        public string Адрес { get; set; }
        public string Услуга { get; set; }
        public Nullable<int> Реквезиты { get; set; }
    }
}
